### ISSUE TITLE
Proposal review

### ISSUE THREAD

**Issue by Chris210634** [Swatkats13/CS506_Final_Project#1]
This sounds like an interesting project and a reasonable proposal.

The only feedback I have is that it would be good to state what the features mean. I understand that the input to the model will be gene expression levels for a handful of genes. But it would be good to explain what the "gene expression level" number means.

**Comment by Swatkats13** [comment]
Hi Chris,

We have added you as a collaborator and created a PR with the necessary changes based on your feedback.
